### ISSUE TITLE
Reward amount incorrect for partial rewards

### ISSUE THREAD

**Issue by walderston** [quentingosset/PlutusAnalyticsDashboard#18]
As per the below image, the reward amount in the subsections is showing the total award. 

I'd have expected to see the values broken down:
i.e. perk reward was 1.0102 PLU and the partial reward was 0.0236 PLU
![image](https://user-images.githubusercontent.com/59405120/228226071-1c2215f3-86e2-41e4-baa9-4e7eff2fc48a.png)

**Comment by quentingosset** [comment]
![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/6824137/fb21ad70-5f5e-416f-b1aa-8598434d34da)
Fixed for next release :)

**Comment by quentingosset** [comment]
Fixed with the new version 1.0.2
