### ISSUE TITLE
Missing icon for account withdrawal to card

### ISSUE THREAD

**Issue by walderston** [quentingosset/PlutusAnalyticsDashboard#20]
Looking at the icons, since the upgrade to the current accounts, the icon is missing for the withdrawal transaction when topping up the card. 

![image](https://user-images.githubusercontent.com/59405120/228790664-5fbe75e1-2501-49a6-96c0-61278d17ebfa.png)

before the current account upgrade, the icon is viewable
![image](https://user-images.githubusercontent.com/59405120/228790785-948e14ba-fd1b-4b6e-9122-730535884daa.png)

**Comment by quentingosset** [comment]
TODO for me : LOAD_PLUTUS_CARD_FROM_WALLET

**Comment by quentingosset** [comment]
Fixed with the new version :-)
