### ISSUE TITLE
what about displaying conversion rate €/PLU for each tx ?

### ISSUE THREAD

**Issue by Peter83** [quentingosset/PlutusAnalyticsDashboard#21]
It would be great to have inside the table the calculated reward in euro for each transaction, based on amount and % of reward, beside this the calculated €/PLU change rate!
Great work, thank you!

**Comment by quentingosset** [comment]
You already have this information ;)
![image](https://user-images.githubusercontent.com/6824137/230638494-ceddc4f5-f85c-4539-b35e-2cc48e304549.png)

**Comment by red9350** [comment]
Would be useful to be able to edit the columns of that table, i.e. adding the Cashback amount or the Rate as a column
