### ISSUE TITLE
Additional transaction data

### ISSUE THREAD

**Issue by walderston** [quentingosset/PlutusAnalyticsDashboard#22]
So this would be an enhancement however it'd be good to have the additional transaction data such as MCC even as a toggle which would add this detail to the overview or a tooltip over the merchant name.

This would aid in trying to understand why a transaction did or didn't qualify for PLU as Curve likes to change the MCC sometimes

**Comment by quentingosset** [comment]
Unfortunately I don't have the information from the MCC via the API. I display the reasons for refusal when they are explicitly written in the database (such as PLU requests made via support, there is usually a reason added).
