### ISSUE TITLE
Chrome webstore link is dead

### ISSUE THREAD

**Issue by dankcushions** [quentingosset/PlutusAnalyticsDashboard#23]
FYI, the link in readme.md appears to be dead: https://chrome.google.com/webstore/detail/plutus-analytics-dashboar/goaipcbpmkahfbcdlpmoamemjhjlpcbm

I couldn't find the extension by searching the webstore either, so I suppose it's removed entirely?

Thanks for your work!

**Comment by walderston** [comment]
@dankcushions you can build it yourself. It’s what I’ve done for now.

**Comment by quentingosset** [comment]
Extension is comeback on chrome store now :)
