### ISSUE TITLE
Suggestion: Please add a link to plutus levels statistics to the menu of the extension

### ISSUE THREAD

**Issue by tschombe** [quentingosset/PlutusAnalyticsDashboard#32]
Hi, 

as a suggestion:
I would love to see a link to the plutus statistics page on the menu of the extension
so there is an easy reference to this nice page:
![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/386133/ccfc4457-e341-4e94-9fab-226fcbf25a74)

linked to:
https://plutus.thomasott.fr/

**Comment by quentingosset** [comment]
I replace "changelog" menu to "on-chain stats" menu on this new release 1.0.7 . The menu redirects to the board I created with @RedBoardDev
