### ISSUE TITLE
Idea: Show "rewards available at TT:MM:YYYY"

### ISSUE THREAD

**Issue by rachoa94** [quentingosset/PlutusAnalyticsDashboard#34]
Hey, I am not sure if that Idea has been already proposed (Github is pretty new for me, so i did not find where i check), but as i mentioned in the Title: 

Maybe you can add a little indicator when rewards will be eligble for withdrawing. Would be neat :)

**Comment by quentingosset** [comment]
![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/6824137/e226580a-405f-4684-b1ad-df6fca28295e)
This feature is already available ;) just put the mouse on the "pending" of the transaction and a tooltip displays the expected delivery date of the cashback (date of reward + 45 days).
