### ISSUE TITLE
subtraction of rewards when refunded

### ISSUE THREAD

**Issue by wusimfan** [quentingosset/PlutusAnalyticsDashboard#40]
How to calculate the correct amount of PLU from refunds?

This example shows a payment of 47,38€ with a reward of 0,3815 PLU.
A week later the amount gets refunded. 
There is no record in the JSON of a refunded reward.
How to match the payment with the refund? There is no unique identifier to match it.
The level of difficulty rises when a payment only gets partly refunded. 

<img width="592" alt="image" src="https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/76494705/b1f6148e-f3a0-4f44-8e05-9f53c7a81a49">

**Comment by quentingosset** [comment]
There's no way because, as you said, there's no correspondence with previous transactions. That's why plutus doesn't withdraw PLU on refund transactions and does this when you go through fraud check.
