### ISSUE TITLE
Error Building 1.0.9

### ISSUE THREAD

**Issue by salimhb** [quentingosset/PlutusAnalyticsDashboard#44]
First thanks for a very helpful extension.

I've built a local version to use in Safari ([following this guide](https://developer.apple.com/news/?id=qiz0arxc))
Version 1.0.8 was building without errors and working very well in Safari. With version 1.0.9, I'm getting error when running `npm run build`:

<details><summary>Build Output</summary>
<p>

```shell
➜  PlutusAnalyticsDashboard git:(main) ✗ npm run build

> Plutus Analytics Dashboard@1.0.9 build
> vite build --mode production

vite v4.5.2 building for production...
✓ 67 modules transformed.
transforming (234) src/css/style.cssZip packing - "extensions/extension_chrome/" folder :
  - Preparing files.
Zip packing - "extensions/extension_firefox/" folder :
  - Preparing files.
✓ built in 2.16s
  - Creating zip archive.
  - Creating zip archive.
  - Done.
  - Done.
Could not resolve "../data/subscription/subscription.json" from "src/utils/PlutusCall.js"
file: /Users/salim/Documents/Projects/Playground/PlutusAnalyticsDashboard/src/utils/PlutusCall.js
error during build:
RollupError: Could not resolve "../data/subscription/subscription.json" from "src/utils/PlutusCall.js"
    at error (file:///Users/salim/Documents/Projects/Playground/PlutusAnalyticsDashboard/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/salim/Documents/Projects/Playground/PlutusAnalyticsDashboard/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
    at file:///Users/salim/Documents/Projects/Playground/PlutusAnalyticsDashboard/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
```

</p>
</details> 

`../data/subscription/subscription.json`, `../data/tiers/levels.json`, `../data/redeem/history.json` and perhaps other json files are missing.

**Comment by quentingosset** [comment]
You need theses files.
I forgot to put on the commit because they contain my own data and i jave forgot to change my private data with fake data.
You can get theses data if you check the network call made from my extension.
For next release, i will update this folder with fake data
![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/6824137/512327a5-8a61-4742-8e11-1339d3cd451f)

**Comment by salimhb** [comment]
Thanks for quick reply :-)

After reading the code referencing them, I noticed that they are not needed in production. I commented their references for now.
