### ISSUE TITLE
Question regarding calculation

### ISSUE THREAD

**Issue by HangLoose1971** [quentingosset/PlutusAnalyticsDashboard#45]
How is the displayed average calculated? Is that the value my PLU had for each respective payment? see enclosed picture.

![image](https://github.com/quentingosset/PlutusAnalyticsDashboard/assets/139506659/47a08c46-4372-4e73-bb2b-8661eb3c9f57)

**Comment by quentingosset** [comment]
> How is the displayed average calculated? Is that the value my PLU had for each respective payment? see enclosed picture.
> 
> ![image](https://private-user-images.githubusercontent.com/139506659/314446187-47a08c46-4372-4e73-bb2b-8661eb3c9f57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjQ1NzQsIm5iZiI6MTcxNjM2NDI3NCwicGF0aCI6Ii8xMzk1MDY2NTkvMzE0NDQ2MTg3LTQ3YTA4YzQ2LTQzNzItNGU3My1iYjJiLTg2NjFlYjNjOWY1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNzUxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWQzMDdkMmIyNGZmYzVlMmJkMDA2ODkzMjg5ZDRmOWY1Y2E0NWJmZTY2ODU3M2ViMDIwM2Y4Yjc3NDdjYjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JVR97wJyOAxxgRUoch2p2NY4YKOfNubo0Hz71fMpsJw)

Is the average price of the PLU you have received over the period you have selected. 
To calculate this, we take the total cashback you've generated divided by the total number of rewards. 
If you've received $100 in rewards over your period, and you've received 5 PLUs, then the average is $20/PLU. 
So you know that over this period the PLU has to be >= $20 for you not to lose any of your cashback earnings.

https://github.com/quentingosset/PlutusAnalyticsDashboard/blob/d5c1e5c94bd68d7c0198aad1cc86741bddf2b1f2/src/components/SpendingOverview.vue#L171
