### ISSUE TITLE
Display Daily, Weekly, and Annual Rolling Limits

### ISSUE THREAD

**Issue by UKmatC** [quentingosset/PlutusAnalyticsDashboard#9]
Display Daily, Weekly, and Annual Rolling Limits (alongside the existing 'Monthly Rolling Limits'.

**Comment by pilot33** [comment]
In addition, I want to see for 30 (and up to 365 days) in the future what the rolling limits W / M / Y will be so I can see when my spending limits free up, i.e. when I can use my card again and plan payments accordingly.

**Comment by ensconce** [comment]
> 

If this feature does not get added you can use https://plu.pay4.se for this, I created this strictly because I was making a couple of large transactions that needed planning.

**Comment by pilot33** [comment]
> > If this feature does not get added you can use https://plu.pay4.se for this, I created this strictly because I was making a couple of large transactions that needed planning.

That is awesome! I built the same table for myself in Excel. With your example/code it might be much easier to integrate it into the AnalyticsDashboard extension.

**Comment by ensconce** [comment]
> That is awesome! I built the same table for myself in Excel. With your example/code it might be much easier to integrate it into the AnalyticsDashboard extension.

Yeah I just uploaded the source to git for reference, I might have a look at Quentins code to see if I could possibly make PR.

**Comment by quentingosset** [comment]
Done in 1.0.4
